import Head from "next/head";
import Link from 'next/link';

import { Container, Header, Banner, LinkSocial, Main, SecondaryTitle, SocialIcons, Text, Title, Carrossel, Buttons, Footer, Menu, Sobre, Projects, ContainerLanguage, SelectLanguage, Project } from "../../components/sharedstyles";
import { useRouter } from "next/router";
import { textsEnglish, textsPotuguese } from "../../utils/texts";
import { useEffect, useState } from "react";
import axios from "axios";

export default function ProjectDescription() {
  const router = useRouter()
  const { asPath } = router
  const parts = asPath.split('/')
  const projectName = parts[parts.length - 1]


  const [ language , setLeguage] = useState("")
  const [ texts, setTexts] = useState([])
  const [projectID, setProjectId] = useState<number>(0)
  const [textsEnglish, setTextsEnglish] = useState([])
  const [textsPotuguese, setTextsPotuguese] = useState([])
  
  const projects = [{name: "Lotudy", description: "Lotudy é uma plataforma de estudos com vários recursos interessantes.", english: "Lotudy is a study platform with several interesting features." , technologies: ["Typescript","Next.js","React","Styled Components","Mongo DB"]},{name: "Adopet",description: "Adopet é uma plataforma de adoção de animais.",english: "Adopet is an animal adoption platform.",technologies: ["React","Typescript","Sass","CSS"]}]

  useEffect(()=>{
    if(language === ""){
        setLeguage("Português")
    }
    const fetchTexts = async () => {
        try {
            const response = await axios.get("/api/texts")
            setTextsPotuguese(response.data.portuguese)
            setTextsEnglish(response.data.english)
        } catch (error) {
            console.log(error)
        }
    }
    fetchTexts()
})

  useEffect(()=>{
      if (language === "English") {
          setTexts(textsEnglish)
      }
      if (language === "Português"){
          setTexts(textsPotuguese)
      }
  },[language])
	
	useEffect(()=>{
		if (projectName !== undefined && projectName !== "Lotudy" && projectName !== "Adopet") {
			router.push("/")
		}
        setProjectId(projects.findIndex((e)=> e.name === projectName))
	})

  return(
    <Container>
            <Head>
                <title>Richard Desenvolvimento de Software  e Soluções.</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com"/>
                <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet"/>
            </Head>
            <Header>
                <SocialIcons>
                    <LinkSocial href="https://www.linkedin.com/in/richard-rodriegues/" >
                        <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linkedin/linkedin-original.svg" alt="linkedin icon" />
                    </LinkSocial>
                    <LinkSocial href="https://github.com/RichardRodriguesGomesDeJesus">
                        <img src="/icons/github-white.svg" alt="github icon" />
                    </LinkSocial>
                </SocialIcons>
                <ContainerLanguage>
                    <SelectLanguage onChange={(e)=> {
                            setLeguage(e.target.value)
                        }} value={language}>
                        <option value="English">English</option>
                        <option value="Português">Português</option>
                    </SelectLanguage>
                </ContainerLanguage>
                <Menu>
                    <Link href={'/'}>
                        Home
                    </Link>
                    <Link href={'/resume_richard.pdf'}>
                        {texts[21]}
                    </Link>
                </Menu>
            </Header>
            <Main>
                <Banner>
                    <Title>{texts[23]}</Title>
                </Banner>
                <Project>
                    <SecondaryTitle>{projects[projectID].name}</SecondaryTitle>
                    <img src={`/img/${projectName}.png`}  />
                    <div>
                        <p>{(language === "Português" ? projects[projectID].description : projects[projectID].english)}</p>
                        <div>
                            <h3>{texts[22]}</h3>
                            <ul>
                            {projects[projectID].technologies.map((e, index)=>(
                                    <li key={index}>{e}</li>
                                ))}
                            </ul>
                        </div>
                    </div>
                </Project>
            </Main>
            <Footer>
                <Menu>
                    <Link href={'/'}>
                        Home
                    </Link>
                    <Link href={'/resume_richard.pdf'}>
                        {texts[21]}
                    </Link>
                </Menu>
                <SocialIcons>
                    <LinkSocial href="https://www.linkedin.com/in/richard-rodriegues/" >
                        <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linkedin/linkedin-original.svg" alt="linkedin icon" />
                    </LinkSocial>
                    <LinkSocial href="https://github.com/RichardRodriguesGomesDeJesus">
                        <img src="/icons/github-white.svg" alt="github icon" />
                    </LinkSocial>
                </SocialIcons>
            </Footer>
        </Container>
  )
}