import Head from "next/head";
import Link from "next/link";
import { Container, Main, Menssage } from "../components/sharedstyles";

export default function Thanks(){
    return(
        <Container>
            <Head>
                <title>Richard.com</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Main>
                <Menssage>
                    <div>
                        <h2>A mensagem foi enviada com sucesso</h2>
                        <Link href={'https://richard-rodrigues-dev.vercel.app/'}>Voltar</Link>
                    </div>
                </Menssage>
            </Main>
        </Container>
    )
}