import Head from "next/head";
import Link from "next/link";
import { Container, ContainerLanguage, Header, LinkSocial, Main, Menssage, SelectLanguage, SocialIcons } from "../components/sharedstyles";
import { useEffect, useState} from "react";
import { textsEnglish, textsPotuguese } from "../utils/texts";

export default function Thanks(){
    const [ language , setLeguage] = useState("English")
    const [ texts, setTexts] = useState([])
    


    useEffect(()=>{
        if (language === "English") {
            setTexts(textsEnglish)
        }
        if (language === "Português"){
            setTexts(textsPotuguese)
        }
    },[language])
    return(
        <Container>
            <Head>
                <title>Richard.com</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header>
                <SocialIcons>
                    <LinkSocial href="https://www.linkedin.com/in/richard-rodriegues/" >
                        <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linkedin/linkedin-original.svg" alt="linkedin icon" />
                    </LinkSocial>
                    <LinkSocial href="https://github.com/RichardRodriguesGomesDeJesus">
                        <img src="icons/github-white.svg" alt="github icon" />
                    </LinkSocial>
                </SocialIcons>
                <ContainerLanguage>
                    <SelectLanguage onChange={(e)=> {
                            setLeguage(e.target.value)
                        }} value={language}>
                        <option value="English">English</option>
                        <option value="Português">Português</option>
                    </SelectLanguage>
                </ContainerLanguage>
            </Header>
            <Main>
                <Menssage>
                    <div>
                        <h2>{texts[25]}</h2>
                        <Link href={'https://www.devrichard.com.br/'}>{texts[26]}</Link>
                    </div>
                </Menssage>
            </Main>
        </Container>
    )
}