import Head from "next/head";
import Link from "next/link";
import { Container, ContainerLanguage, Header, LinkSocial, Main, Menssage, SelectLanguage, SocialIcons } from "../components/sharedstyles";
import { useEffect, useState} from "react";
import { textsEnglish, textsPotuguese } from "../utils/texts";

export default function Thanks(){
    const [ language , setLanguage] = useState("")
    const [ texts, setTexts] = useState([])
    useEffect(()=>{
        const localLang = localStorage.getItem("language")
        console.log(localLang)
        if(localLang === null){
            const userLang = navigator.language;
            if (userLang == "pt-BR") {
                setLanguage("Português")
                localStorage.setItem("language","Português")
                setTexts(textsPotuguese)
            } else{
                setLanguage("English")
                localStorage.setItem("language","English")
                setTexts(textsEnglish)
            }
        } else {
            const lang = localStorage.getItem("language")
            if (lang === "Português" ) {
                setLanguage("Português")
                setTexts(textsPotuguese)
            } else{
                setLanguage("English")
                setTexts(textsEnglish)
            }
        }
    },[language === ""])
    useEffect(()=>{
        if (language === "English") {
            setTexts(textsEnglish)
            localStorage.removeItem("language")
            localStorage.setItem("language","English")
        }
        if (language === "Português"){
            setTexts(textsPotuguese)
            localStorage.removeItem("language")
            localStorage.setItem("language","Português")
        }
    },[language])
    return(
        <Container>
            <Head>
                <title>Richard Desenvolvimento de Software  e Soluções.</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com"/>
                <link href="https://fonts.googleapis.com/css2?family=Krona+One&display=swap" rel="stylesheet"/>
            </Head>
            <Header>
                <SocialIcons>
                    <LinkSocial href="https://www.linkedin.com/in/richard-rodriegues/" >
                        <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linkedin/linkedin-original.svg" alt="linkedin icon" />
                    </LinkSocial>
                    <LinkSocial href="https://github.com/RichardRodriguesGomesDeJesus">
                        <img src="/icons/github-white.svg" alt="github icon" />
                    </LinkSocial>
                </SocialIcons>
                <ContainerLanguage>
                    <SelectLanguage onChange={(e)=> {
                            setLanguage(e.target.value)
                        }} value={language}>
                        <option value="English">English</option>
                        <option value="Português">Português</option>
                    </SelectLanguage>
                </ContainerLanguage>
            </Header>
            <Main>
                <Menssage>
                    <div>
                        <h2>{texts[19]}</h2>
                        <Link href={'https://www.devrichard.com.br/'}>{texts[20]}</Link>
                    </div>
                </Menssage>
            </Main>
        </Container>
    )
}
